"""Reproducible (re)generation of the BSM ``mixed_grid_lifecycle`` frozen corpus.

The ``default`` three-stage ``blind_spectrum_monitoring`` schedule — the one the
concept-drift-on-reset-boundary experiments need — declares
``corpus_id: mixed_grid_lifecycle`` on every stage. CL-Bench refuses to fall
back to seed-driven scans when a schedule names a corpus: constructing the task
raises ``FileNotFoundError`` unless the frozen corpus is on disk
(``task.py:_init_frozen_corpus``).

### Where the corpus lives

It ships **git-tracked inside the cl-benchmark dependency**, at
``<cl-bench>/data/blind_spectrum_monitoring/mixed_grid_lifecycle{.jsonl,_metadata.json}``
(``corpus.default_corpus_paths``). A freshly cloned cl-bench therefore already
has it — for most readers "locate" is the whole story and this module never
needs to run.

### Why a regenerator anyway

The corpus is **byte-deterministic**: each stage is a seeded ``SpectrumDGP``
rollout (seeds 42/43/44 in ``schedules/default.json``), so re-materialising it
reproduces the committed bytes exactly (sha256
``89be0c2d1528c59ddae47b67747bbe551ca138a3f27fb6f2bcfdd496c5086ae7``). This
module wraps CL-Bench's own ``build_rollout_corpus`` + ``write_scan_corpus`` so
that:

* a genuinely-missing corpus can be regenerated in place (``--force`` / default),
* and provenance is checkable — :func:`verify_corpus` regenerates into a temp
  dir and compares the sha256 to whatever is on disk, mutating nothing.

The on-disk artifact is the source of truth for *running*; this regenerator is
the source of truth for *reproducing*.

### CLI

    # verify the committed corpus reproduces byte-for-byte (no writes):
    python -m retention_bench.bsm_corpus --verify
    # (re)write it into the cl-bench data dir if missing or stale:
    python -m retention_bench.bsm_corpus
    # force-overwrite even when present:
    python -m retention_bench.bsm_corpus --force

Run with an interpreter that has cl-benchmark installed (Python >= 3.13),
e.g.::

    python -m retention_bench.bsm_corpus --verify
"""

from __future__ import annotations

import argparse
import hashlib
import tempfile
from pathlib import Path
from typing import Optional, Sequence

from ._clbench import (
    build_rollout_corpus,
    default_corpus_paths,
    write_scan_corpus,
)

ROLLOUT_SCHEDULE_ID = "default"
CORPUS_ID = "mixed_grid_lifecycle"

# The committed corpus's content hash. A regeneration that does not reproduce
# this is a regression (a changed DGP, variant defaults, or schedule seed).
EXPECTED_SHA256 = "89be0c2d1528c59ddae47b67747bbe551ca138a3f27fb6f2bcfdd496c5086ae7"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def corpus_paths() -> tuple[Path, Path]:
    """``(jsonl_path, metadata_path)`` of the corpus in the cl-bench data dir."""
    return default_corpus_paths(CORPUS_ID)


def materialize_to(jsonl_path: Path, metadata_path: Path) -> str:
    """Build the ``default`` rollout and write it to the given paths.

    Returns the sha256 of the written ``.jsonl``. Pure I/O of a deterministic
    build — callers decide *where* (the canonical data dir, or a temp dir for
    verification).
    """
    rows, metadata = build_rollout_corpus(ROLLOUT_SCHEDULE_ID, corpus_id=CORPUS_ID)
    jsonl_path.parent.mkdir(parents=True, exist_ok=True)
    final = write_scan_corpus(
        rows, metadata, jsonl_path=jsonl_path, metadata_path=metadata_path
    )
    return final.jsonl_sha256 or _sha256(jsonl_path)


def verify_corpus() -> tuple[bool, str, Optional[str]]:
    """Regenerate into a temp dir; compare to the committed hash and on-disk file.

    Mutates nothing on the canonical data dir. Returns
    ``(ok, regenerated_sha, on_disk_sha_or_None)`` where ``ok`` means the
    regenerated bytes match :data:`EXPECTED_SHA256` *and* (when present) the
    on-disk corpus.
    """
    tmp = Path(tempfile.mkdtemp(prefix="bsm-corpus-verify-"))
    regen_sha = materialize_to(
        tmp / f"{CORPUS_ID}.jsonl", tmp / f"{CORPUS_ID}_metadata.json"
    )
    jsonl_path, _ = corpus_paths()
    on_disk_sha = _sha256(jsonl_path) if jsonl_path.exists() else None
    ok = regen_sha == EXPECTED_SHA256 and (
        on_disk_sha is None or on_disk_sha == regen_sha
    )
    return ok, regen_sha, on_disk_sha


def ensure_corpus(*, force: bool = False) -> tuple[Path, str, bool]:
    """Ensure the corpus exists in the cl-bench data dir; (re)write if needed.

    Returns ``(jsonl_path, sha256, wrote)``. Skips the write when both files are
    already present and ``force`` is false (the common case — it ships tracked).
    """
    jsonl_path, metadata_path = corpus_paths()
    if not force and jsonl_path.exists() and metadata_path.exists():
        return jsonl_path, _sha256(jsonl_path), False
    sha = materialize_to(jsonl_path, metadata_path)
    return jsonl_path, sha, True


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m retention_bench.bsm_corpus",
        description="Regenerate / verify the BSM mixed_grid_lifecycle frozen corpus.",
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--verify",
        action="store_true",
        help="Regenerate into a temp dir and compare to the committed hash + "
        "on-disk corpus. Writes nothing. Exit 0 iff reproducible.",
    )
    group.add_argument(
        "--force",
        action="store_true",
        help="Overwrite the corpus in the cl-bench data dir even if present.",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    if args.verify:
        ok, regen_sha, on_disk_sha = verify_corpus()
        print(f"regenerated sha256 : {regen_sha}")
        print(f"expected    sha256 : {EXPECTED_SHA256}")
        print(f"on-disk     sha256 : {on_disk_sha or '(absent)'}")
        print("REPRODUCIBLE" if ok else "MISMATCH")
        return 0 if ok else 1

    jsonl_path, sha, wrote = ensure_corpus(force=args.force)
    verb = "wrote" if wrote else "present (unchanged)"
    flag = "" if sha == EXPECTED_SHA256 else "  [!] sha != expected"
    print(f"{verb}: {jsonl_path}")
    print(f"sha256: {sha}{flag}")
    return 0 if sha == EXPECTED_SHA256 else 1


if __name__ == "__main__":  # pragma: no cover - CLI entrypoint
    raise SystemExit(main())
