"""CL-Bench entrypoint for the constructive (train-and-grow) SUT.

The book-track entrypoint (``constructive.__main__``) speaks the READ/QUIZ
event contract. Continual Learning Bench, driven through
``retention_bench.SubprocessSystem``, speaks a different one-line-JSON contract:

  request  (harness -> SUT):
    {"prompt": str, "instance_id": str|null, "instance_index": int|null,
     "response_schema": {<JSON Schema>}, "feedback": str|null}
  reply    (SUT -> harness):
    {"action": {<fields matching response_schema>},
     "resource": {"flops": int, "tokens_in": int, "tokens_out": int,
                  "model_id": str, ...}}

This module bridges the constructive SUT onto that contract while keeping
``SubprocessSystem`` generic (a deliberate design call). It reuses ``model``/``train``/
``checkpoint``/``grow`` verbatim:

  * each query → a bounded gradient step on the *prompt* bytes (the "learning"
    signal: there is no separate READ stage in CL-Bench's single-shot tasks);
  * capacity grows on a schedule (default: once, on the first instance), so a
    fresh process *constructs* a larger model mid-run;
  * a full checkpoint is flushed to the survive-dir *before* the reply, so it
    survives the SIGKILL of a hard RESET;
  * the action is synthesised from the query's ``response_schema`` with values
    derived from the model's (gibberish) generation — schema-valid so the
    runner's ``response_schema(**fields)`` never raises, model-derived so the
    output genuinely reflects the constructed weights.

**Output quality is an explicit NON-GOAL** (see the package docstring).
This SUT exists to prove the plumbing — that a weights-mutating,
capacity-growing system can run as a CL-Bench system, persist through a hard
reset, and be accounted for in the compute channel. The real constructive
transformer is developed elsewhere; reward-gain on the task is expected to be
uninformative by construction.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any, Iterable, Iterator

from . import checkpoint as ckpt
from . import train as trainer
from .model import ModelConfig, grow, text_to_ids

# Growth policy. Grow once when this (1-based) instance completes, mirroring the
# book-track SUT's GROW_AFTER_READ_INDEX. An optional cadence (grow every N
# instances) and a layer cap keep richer growth schedules a config change, not a
# code change.
GROW_AFTER_INSTANCE = 1

# Bytes of gibberish to generate per query (seeds the synthesised action).
# Quality is a non-goal; keep it short/fast on CPU.
GEN_BYTES = 24


def _die(msg: str, code: int = 1) -> None:
    print(f"constructive SUT (clbench): {msg}", file=sys.stderr, flush=True)
    sys.exit(code)


def _dir_path() -> Path:
    # cwd is the survive-dir per the contract; RETENTION_BENCH_DIR echoes it.
    return Path(os.environ.get("RETENTION_BENCH_DIR", os.getcwd()))


def _default_config() -> ModelConfig:
    """Allow env overrides for tiny test configs; defaults stay smoke-safe."""

    def _int(name: str, default: int) -> int:
        v = os.environ.get(name)
        return int(v) if v else default

    return ModelConfig(
        block_size=_int("CONSTRUCTIVE_BLOCK_SIZE", 64),
        d_model=_int("CONSTRUCTIVE_D_MODEL", 64),
        n_heads=_int("CONSTRUCTIVE_N_HEADS", 4),
        n_layers=_int("CONSTRUCTIVE_N_LAYERS", 2),
    )


def _load_state(dir_path: Path) -> ckpt.State:
    seed = int(os.environ.get("CONSTRUCTIVE_SEED", "0"))
    if ckpt.has_checkpoint(dir_path):
        return ckpt.load(dir_path)
    return ckpt.cold_init(_default_config(), seed=seed)


def _grow_every() -> int:
    v = os.environ.get("CONSTRUCTIVE_GROW_EVERY")
    return int(v) if v else 0


def _max_layers() -> int:
    v = os.environ.get("CONSTRUCTIVE_MAX_LAYERS")
    return int(v) if v else 6


def _should_grow(read_count: int, n_layers: int) -> bool:
    if n_layers >= _max_layers():
        return False
    if read_count == GROW_AFTER_INSTANCE:
        return True
    every = _grow_every()
    return every > 0 and read_count % every == 0


# --------------------------------------------------------------------------- #
# Generic JSON-Schema -> value synthesiser.
#
# Handles exactly the subset CL-Bench response models use (object/array/number/
# integer/boolean/string, $ref into $defs). Anything outside that subset raises
# loudly rather than guessing — better a clear failure than a silent invalid
# action that crashes the runner downstream.
# --------------------------------------------------------------------------- #
class _ByteStream:
    """A never-ending stream of model-generated bytes (cycled if exhausted)."""

    def __init__(self, gibberish: Iterable[int]) -> None:
        self._buf = [b & 0xFF for b in gibberish] or [0]
        self._pos = 0

    def next(self) -> int:
        b = self._buf[self._pos % len(self._buf)]
        self._pos += 1
        return b


def _resolve_ref(ref: str, defs: dict[str, Any]) -> dict[str, Any]:
    prefix = "#/$defs/"
    if not ref.startswith(prefix):
        _die(f"unsupported $ref {ref!r} (only #/$defs/* is handled)")
    name = ref[len(prefix) :]
    if name not in defs:
        _die(f"$ref {ref!r} not found in $defs")
    return defs[name]


def _synthesize(schema: dict[str, Any], defs: dict[str, Any], bs: _ByteStream) -> Any:
    if "$ref" in schema:
        return _synthesize(_resolve_ref(schema["$ref"], defs), defs, bs)

    typ = schema.get("type")
    if typ == "object":
        props: dict[str, Any] = schema.get("properties", {})
        required = schema.get("required", list(props.keys()))
        return {
            name: _synthesize(props[name], defs, bs)
            for name in required
            if name in props
        }
    if typ == "array":
        item_schema = schema.get("items", {})
        min_items = int(schema.get("minItems", 0))
        # 0..3 gibberish items (at least minItems), so stateful vs wiped runs
        # produce *different* reports without ever exploding in size.
        count = max(min_items, bs.next() % 4)
        return [_synthesize(item_schema, defs, bs) for _ in range(count)]
    if typ == "number":
        # b1 + b2/256 → a float in [0, 256); plausible-ish, deterministic, junk.
        return float(bs.next()) + bs.next() / 256.0
    if typ == "integer":
        return bs.next()
    if typ == "boolean":
        return bool(bs.next() & 1)
    if typ == "string":
        n = 1 + (bs.next() % 8)
        return bytes(bs.next() for _ in range(n)).decode("latin-1")

    _die(f"unsupported JSON Schema node (type={typ!r}, keys={sorted(schema)})")


def _synthesize_action(response_schema: dict[str, Any], gibberish: list[int]) -> dict[str, Any]:
    defs = response_schema.get("$defs", {})
    bs = _ByteStream(gibberish)
    action = _synthesize(response_schema, defs, bs)
    if not isinstance(action, dict):
        _die("top-level response_schema must be an object")
    return action


# --------------------------------------------------------------------------- #
# Per-query handling.
# --------------------------------------------------------------------------- #
def _handle_query(state: ckpt.State, dir_path: Path, request: dict) -> dict:
    prompt = request.get("prompt", "") or ""
    ids = text_to_ids(prompt)

    flops_before = state.meta.train_flops
    steps = trainer.train_on_text(state, ids)
    state.meta.read_count += 1

    grew = False
    if _should_grow(state.meta.read_count, state.config.n_layers):
        state.model = grow(state.config, state.model)
        state.config = state.model.cfg
        state.meta.growth_count += 1
        grew = True

    # FLUSH the checkpoint BEFORE replying — survives an immediate RESET.
    ckpt.save(dir_path, state)

    # Gibberish generation from current weights; seeds the synthesised action.
    prompt_ids = ids[: state.config.block_size] or [text_to_ids("")[0]]
    gen = state.model.generate(prompt_ids, max_new_tokens=GEN_BYTES)

    response_schema = request.get("response_schema") or {"type": "object", "properties": {}}
    action = _synthesize_action(response_schema, gen)

    resource = {
        "flops": int(state.meta.train_flops - flops_before),
        "tokens_in": len(ids),
        "tokens_out": len(gen),
        "model_id": "constructive",
        "param_count": state.model.param_count(),
        "growth_count": state.meta.growth_count,
        "n_layers": state.config.n_layers,
        "train_steps_this_query": steps,
        "grew": grew,
    }
    return {"action": action, "resource": resource}


def _iter_requests(stream: Iterable[str]) -> Iterator[dict]:
    for line in stream:
        line = line.strip()
        if line:
            yield json.loads(line)


def main() -> None:
    try:
        import torch  # noqa: F401
    except ImportError:
        _die("`torch` is not installed (pip install torch). CPU build is fine.", code=2)

    dir_path = _dir_path()
    state = _load_state(dir_path)

    for request in _iter_requests(sys.stdin):
        reply = _handle_query(state, dir_path, request)
        sys.stdout.write(json.dumps(reply, ensure_ascii=False) + "\n")
        sys.stdout.flush()


if __name__ == "__main__":
    main()
