#!/usr/bin/env python3
"""Read ``decisions/*.md`` and render the machine-facing copies.

The decision record is authored as one markdown document per decision, because
that is what it is: a short document a person reads and edits, not config. The
repo already keeps its authored records this way (``.tasks/*.md``,
``notebook/notes/*.md``) and reserves JSONL for machine-appended streams
(``.tasks/LOG.jsonl``); this follows that line rather than inventing a third
shape.

Two renderings are generated from it, and **neither is authored by hand**:

* ``pages/decisions.js``  — a ``<script>``-loadable const for the map page.
  Generated rather than fetched because ``file://`` blocks ``fetch``, so a
  data file the page fetches would work on Pages and break locally.
* ``decisions/INDEX.md``  — the whole map on one screen, which is the one thing
  a directory of documents costs you.

Usage::

    python tools/decisions.py build    # regenerate both
    python tools/decisions.py check    # fail if either is stale (CI)

Document shape — prose first, machine fields last, so the file reads as prose:

    # Title
    *hint*
    ## Summary / ## Why / ## What it buys / ## Trade-off / ## Leads to
    ## Source
    ```toml
    id = "..."
    depth = "..."
    [source]
    path = "..."
    symbol = "..."   # or heading = "..."
    ```
"""

from __future__ import annotations

import json
import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DECISIONS_DIR = REPO_ROOT / "decisions"
PAGES_JS = REPO_ROOT / "pages" / "decisions.js"
INDEX_MD = DECISIONS_DIR / "INDEX.md"

# Section heading -> record key. The headings are the reader-facing wording;
# the keys are what map.js already consumes.
# Heading -> record key. The headings borrow the architecture-decision-record
# vocabulary (context/decision/consequences) rather than inventing one; the keys
# are the older names map.js already consumes, kept stable so a heading rename
# does not ripple into the renderers.
SECTIONS = {
    "Decision": "summary",
    "Context": "why",
    "Gains": "buys",
    "Costs": "tradeoff",
    "See also": "leads",
}

TOML_FENCE_RE = re.compile(r"```toml\n(.*?)```", re.S)
BANNER = "// Generated by tools/decisions.py from decisions/*.md — do not edit.\n"


class DecisionError(ValueError):
    """A decision document is malformed. Message names the file and the fix."""


def _split_sections(body: str) -> dict[str, str]:
    """``## Heading`` -> paragraph text, with the fenced block left alone."""
    out: dict[str, str] = {}
    current: str | None = None
    buf: list[str] = []
    in_fence = False
    for line in body.splitlines():
        if line.startswith("```"):
            in_fence = not in_fence
        if not in_fence and line.startswith("## "):
            if current:
                out[current] = "\n".join(buf).strip()
            current, buf = line[3:].strip(), []
            continue
        if current:
            buf.append(line)
    if current:
        out[current] = "\n".join(buf).strip()
    return out


def _unwrap(text: str) -> str:
    """Re-join hard-wrapped prose into the single logical sentence it is.

    The documents wrap at 78 columns so they read and diff well; the consumers
    want the unbroken string. Blank lines would mean real paragraph breaks, but
    no field has one today — reject rather than silently flatten, so that if a
    field ever grows a paragraph we notice here instead of in the rendered page.
    """
    if "\n\n" in text:
        raise DecisionError("multi-paragraph field; the renderers assume one paragraph")
    return " ".join(text.split())


def load() -> list[dict]:
    """Every decision, ordered by filename prefix."""
    files = sorted(p for p in DECISIONS_DIR.glob("*.md") if p.name != "INDEX.md")
    if not files:
        raise DecisionError(f"no decision documents in {DECISIONS_DIR}")

    records = []
    for path in files:
        text = path.read_text(encoding="utf-8")
        rel = path.relative_to(REPO_ROOT)

        if not (m := re.match(r"#\s+(.+)", text)):
            raise DecisionError(f"{rel}: no `# Title` on the first line")
        title = m.group(1).strip()

        if not (h := re.search(r"^\*([^*]+)\*\s*$", text, re.M)):
            raise DecisionError(f"{rel}: no `*hint*` line under the title")
        hint = h.group(1).strip()

        sections = _split_sections(text)
        if "Source" not in sections:
            raise DecisionError(f"{rel}: no `## Source` section")
        if not (f := TOML_FENCE_RE.search(sections["Source"])):
            raise DecisionError(f"{rel}: `## Source` has no ```toml fence")

        try:
            meta = tomllib.loads(f.group(1))
        except tomllib.TOMLDecodeError as exc:
            raise DecisionError(f"{rel}: malformed toml fence: {exc}") from exc

        record = {"id": meta.get("id"), "depth": meta.get("depth"), "title": title, "hint": hint}
        for heading, key in SECTIONS.items():
            if heading not in sections:
                raise DecisionError(f"{rel}: missing `## {heading}` section")
            try:
                record[key] = _unwrap(sections[heading])
            except DecisionError as exc:
                raise DecisionError(f"{rel}: `## {heading}`: {exc}") from exc
        record["source"] = meta.get("source")

        missing = [k for k, v in record.items() if not v]
        if missing:
            raise DecisionError(f"{rel}: empty or absent field(s): {', '.join(missing)}")
        src = record["source"]
        if "path" not in src or not ({"symbol", "heading"} & src.keys()):
            raise DecisionError(f"{rel}: [source] needs `path` and one of `symbol`/`heading`")
        if path.stem.split("-", 1)[-1] != record["id"]:
            raise DecisionError(f"{rel}: filename does not match id `{record['id']}`")
        records.append(record)

    if len(ids := [r["id"] for r in records]) != len(set(ids)):
        raise DecisionError(f"duplicate decision ids: {ids}")
    return records


def render_js(records: list[dict]) -> str:
    return BANNER + "const nodes = " + json.dumps(records, indent=2, ensure_ascii=False) + ";\n"


def render_index(records: list[dict]) -> str:
    """The whole map on one screen — what a directory of documents costs you."""
    lines = [
        "<!-- Generated by tools/decisions.py from decisions/*.md — do not edit. -->",
        "",
        "# Decision record",
        "",
        "Why each piece of Retention Bench exists, ordered from the research",
        "question down to the code. One document per decision; this index is",
        "generated from them.",
        "",
        "| # | Decision | Depth | Anchor |",
        "|---|---|---|---|",
    ]
    for i, r in enumerate(records, 1):
        s = r["source"]
        anchor = f"`{s['path']}` — {s.get('symbol') or s.get('heading')}"
        lines.append(f"| {i:02d} | [{r['title']}]({i:02d}-{r['id']}.md) | {r['depth']} | {anchor} |")
    return "\n".join(lines) + "\n"


TARGETS = ((PAGES_JS, render_js), (INDEX_MD, render_index))


def main(argv: list[str]) -> int:
    mode = argv[1] if len(argv) > 1 else "build"
    if mode not in ("build", "check"):
        print(__doc__)
        return 2
    try:
        records = load()
    except DecisionError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    stale = []
    for target, render in TARGETS:
        wanted = render(records)
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if mode == "build":
            target.write_text(wanted, encoding="utf-8")
        elif current != wanted:
            stale.append(target.relative_to(REPO_ROOT).as_posix())

    if stale:
        print(
            "error: generated file(s) out of date with decisions/: "
            + ", ".join(stale)
            + "\n       run `python tools/decisions.py build` and commit the result.",
            file=sys.stderr,
        )
        return 1
    print(f"{'wrote' if mode == 'build' else 'checked'} {len(TARGETS)} file(s) from {len(records)} decisions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
